### ISSUE TITLE
DecomPy Git Organization Lacks Cool Icon

### ISSUE THREAD

**Issue by racuna1** [DecomPy/DecomPy#34]
DecomPy needs a memorable icon that people will associate with the project.

**Comment by zlmonroe** [comment]
Resolved in US138-binary-lifting

**Comment by yzgarrard** [comment]
The "p" in "Decompy" is lowercase, and it makes not sense. It should be capitalized into "DecomPy".

**Comment by zlmonroe** [comment]
Resolved.
